### PR TITLE
Scroll through the list to read the whole thing

### LINKED ISSUE #22: Can't seem to get more than 13 items
It seems that if the Alexa list has more than 13 elements, the ones at the bottom aren't listed by `get_alexa_list`. Is this happening to anybody else?

### PR DESCRIPTION
**Pull request by alexiri**
Closes #22.

A side effect of this approach is that duplicate items in the list are filtered, but unfortunately there's no other way to uniquely identify list items.

### CODE REVIEW

**Comment by madmachinations** [comment]
Oooo interesting! Looks good from a glance, did you check if this still works when the list contains 27 or more items?

**Comment by alexiri** [comment]
Yes:

```
2024-10-12 21:15:36.892 INFO server - <module>: Alexa list: ['30', '29', '28', '27', '26', '25', '24', '23', '22', '21', '20', '19', '18', '17', '16', '15', '14', '13', '12', '11', '10', '9', '8', '7', '6', '5', '4', '3', '2', '1']
2024-10-12 21:15:36.892 INFO server - <module>: 30 items in Alexa list
```

But then I ran it again and got this error, so I guess more testing is needed:

```
Traceback (most recent call last):
  File "/server/server.py", line 116, in <module>
    alexa_list = alexa.get_alexa_list(refresh=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/server/alexa.py", line 250, in get_alexa_list
    if item.get_attribute('innerText') not in found:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 178, in get_attribute
    attribute_value = self.parent.execute_script(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 414, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=129.0.6668.70); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
```

**Comment by alexiri** [comment]
With the added sleep, this seems to work reliably for me.

**Comment by raidolo** [comment]
There's a bug somewhere cause with an empty list I'm getting this in the container logs: 

```
IndexError: list index out of range
connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/websockets/legacy/server.py", line 245, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3.12/site-packages/websockets/legacy/server.py", line 1188, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/server/server.py", line 271, in _process_command
    results = await _route_command(command, arguments)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/server/server.py", line 245, in _route_command
    return await _cmd_get_shopping_list()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/server/server.py", line 187, in _cmd_get_shopping_list
    result = instance.get_alexa_list(), None
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/server/alexa.py", line 251, in get_alexa_list
    if last == list_items[-1]:
               ~~~~~~~~~~^^^^
IndexError: list index out of range

```

**Comment by raidolo** [comment]
The previous commet was for @alexiri :)

**Pull request merged**
